/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Capsule v1 — trace-anchored record/replay schema.
 *
 * A **Capsule** is the deterministic-improvement primitive: the OTel trace an
 * agent emitted on its first ("record") run, plus the external I/O that
 * produced each span, content-addressed and frozen. Replaying any later agent
 * revision against a capsule serves the recorded I/O at the span boundaries,
 * so the new run's trace differs from the recorded one *only* where the
 * agent's own logic changed. The judge then evaluates that diff with full
 * provenance — improvement becomes verifiable instead of statistically noisy.
 *
 * Traces are the substrate (not derived trajectory): `recorded_trace` is the
 * same `Span[]` shape the rest of Agent Health already understands, so a
 * capsule's trace is compatible with `processSpansIntoTree`,
 * `categorizeSpanTree`, and `compareTraces` out of the box.
 *
 * This file is the **spec** — every other capsule component (record middleware,
 * replay engine, diff judge, CLI) fits to these types. Design + phasing:
 * https://github.com/opensearch-project/agent-health/issues/323
 *
 * NOTE: `recorded_trace.spans` is validated structurally here (a permissive
 * passthrough that mirrors `types#Span`) rather than re-deriving the full Span
 * zod schema, to avoid this spec drifting from the canonical TS type.
 */

import { z } from 'zod';

export const CAPSULE_SCHEMA_VERSION = '1.0' as const;

/** A single external I/O kind the replay engine can serve. */
export const IoKindSchema = z.enum(['llm_response', 'tool_result', 'simulated_user_turn']);
export type IoKind = z.infer<typeof IoKindSchema>;

/** How a simulated user turn was produced on the record run. */
export const TurnSourceSchema = z.enum(['ai_simulator', 'scripted', 'human']);
export type TurnSource = z.infer<typeof TurnSourceSchema>;

/**
 * One frozen external response, keyed by the span that emitted it. On replay,
 * the engine matches by (kind, span_id) and falls back to
 * `request_canonical_hash` when span ids are regenerated by the candidate run.
 */
export const IoResponseSchema = z.object({
  span_id: z.string().min(1),
  kind: IoKindSchema,
  /** Canonical hash of the *request* that produced this response (order-stable). */
  request_canonical_hash: z.string().min(1),
  /** The frozen response payload. Shape depends on `kind`; opaque to the schema. */
  response: z.unknown(),
  // Fields specific to simulated_user_turn:
  trigger: z.string().optional(),
  generated_by: TurnSourceSchema.optional(),
  simulator_seed: z.number().int().optional(),
  persona: z.string().optional(),
});
export type IoResponse = z.infer<typeof IoResponseSchema>;

/** Telemetry-contract conformance computed at record time (audit primitive). */
export const ContractConformanceSchema = z.object({
  contract_version: z.string().optional(),
  required_spans_emitted: z.array(z.string()).default([]),
  required_spans_missing: z.array(z.string()).default([]),
  required_attrs_complete: z.boolean().default(true),
  /** 1.0 = emitted everything the contract declared. */
  coverage_score: z.number().min(0).max(1).default(1),
});
export type ContractConformance = z.infer<typeof ContractConformanceSchema>;

/** The baseline judge verdict captured at record time — the bar replay compares against. */
export const BaselineJudgmentSchema = z.object({
  judge_id: z.string(),
  pass: z.boolean(),
  reasoning: z.string().optional(),
  score: z.number().optional(),
  judged_on: z.literal('span_tree').default('span_tree'),
});
export type BaselineJudgment = z.infer<typeof BaselineJudgmentSchema>;

/**
 * Minimal structural validation of a recorded span. Mirrors `types#Span`
 * (passthrough keeps forward-compat fields like `events`, `children`, `depth`).
 */
export const RecordedSpanSchema = z
  .object({
    traceId: z.string(),
    spanId: z.string(),
    parentSpanId: z.string().optional(),
    name: z.string(),
    startTime: z.string(),
    endTime: z.string(),
    status: z.enum(['OK', 'ERROR', 'UNSET']),
    attributes: z.record(z.unknown()).optional(),
  })
  .passthrough();

export const RecordedTraceSchema = z.object({
  trace_id: z.string().min(1),
  spans: z.array(RecordedSpanSchema).min(1),
});
export type RecordedTrace = z.infer<typeof RecordedTraceSchema>;

/** The pinned identity of the run that produced the capsule. */
export const RecordedAgainstSchema = z.object({
  agent: z.string(),
  rev: z.string(),
  model: z.string().optional(),
  config_hash: z.string().optional(),
  recorded_at: z.string(), // ISO-8601
});
export type RecordedAgainst = z.infer<typeof RecordedAgainstSchema>;

/** Capsule v1 — the full artifact. Content-addressed by `capsule_hash`. */
export const CapsuleSchema = z.object({
  schema_version: z.literal(CAPSULE_SCHEMA_VERSION),
  /** sha256 over the canonicalized capsule body (excluding this field). */
  capsule_hash: z.string().min(1),
  test_case_id: z.string().min(1),
  test_case_version: z.number().int().nonnegative().optional(),
  recorded_against: RecordedAgainstSchema,
  recorded_trace: RecordedTraceSchema,
  io_responses: z.array(IoResponseSchema).default([]),
  contract_conformance: ContractConformanceSchema.optional(),
  baseline_judgment: BaselineJudgmentSchema.optional(),
});
export type Capsule = z.infer<typeof CapsuleSchema>;

/** The body that gets hashed — everything except the hash field itself. */
export type CapsuleBody = Omit<Capsule, 'capsule_hash'>;

/**
 * Validate an unknown value as a Capsule. Throws ZodError on failure.
 * Use at every trust boundary (load from storage, accept over the wire).
 */
export function parseCapsule(input: unknown): Capsule {
  return CapsuleSchema.parse(input);
}

/** Non-throwing variant. */
export function safeParseCapsule(input: unknown): z.SafeParseReturnType<unknown, Capsule> {
  return CapsuleSchema.safeParse(input);
}
